name: Create Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        
    - name: Get version from manifest
      id: get_version
      run: |
        VERSION=$(node -p "require('./manifest.json').version")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "tag=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
        
    - name: Create distribution directory
      run: mkdir -p dist
      
    - name: Create Chrome Web Store package
      run: |
        zip -r "dist/google-meet-chat-to-clipboard-v${{ steps.get_version.outputs.version }}.zip" \
          manifest.json \
          content.js \
          modules/ \
          images/ \
          _locales/ \
          -x "*.DS_Store"
          
    - name: Verify package contents
      run: |
        echo "Package contents:"
        unzip -l "dist/google-meet-chat-to-clipboard-v${{ steps.get_version.outputs.version }}.zip"
        
    - name: Create Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ steps.get_version.outputs.tag }}
        name: Release ${{ steps.get_version.outputs.tag }}
        body: |
          Chrome Web Store package for version ${{ steps.get_version.outputs.version }}
          
          ## Installation
          1. Download the zip file below
          2. Upload to Chrome Web Store or load as unpacked extension
          
          ## Changes
          See [README](README.md) for details.
        draft: false
        prerelease: false
        files: |
          dist/google-meet-chat-to-clipboard-v${{ steps.get_version.outputs.version }}.zip